export class ContactsFakeDb
{
    public static contacts = [
      {
        'id': '1',
        'CommissionType': 'CommissionType',
        'CommissionInfo': 'CommissionInfo',
        'Status': 'Status',
        'Salutation': 'Salutation',
        'Dearline': 'Dearline',
        'LeadSource': 'LeadSource',
        'Lead': 'Lead',
        'Budget': 'Budget',
        'BuildinF': 'BuildinF',
        'BuildinS': 'BuildinS',
        'BuildSite': 'BuildSite',
        'Nearesttown': 'Nearesttown',
        'Contractor': 'Contractor',
        'Builder': 'Builder',
        'Buildertel': 'Buildertel',
        'Customerfname': 'JAS',
        'Customerlname': 'Alias',
        'Partnerfname': 'Partnerfname',
        'Partnerlname': 'Partnerlname',
        'Contractname': 'Contractname',
        'PotentialValue': 'PotentialValue',
        'DateEntered': 'DateEntered',
        'ContactNameLocked': '1/18/2018',
        'FormF': 'FormF',
        'FormS': 'true',
        'SiteServiced': 'true',
        'Siteplan': 'true',
        'DesignBudget': 'true',
        'FromwebFormf': 'FromwebFormf',
        'FromwebFormS': 'FromwebFormS',
        'Comments': 'Comments',
        'address1': 'address1',
        'Hometel': 'Hometel',
        'Address2': 'Address2',
        'Bussinesstel': 'Bussinesstel',
        'City': 'City',
        'Cellulartel': 'Cellulartel',
        'Country': 'Country',
        'email': 'email',
        'State': 'State',
        'email2': 'email2',
        'zipCode': 'zipCode',
        'ContactedVia': 'ContactedVia',
        'DPSJobstatus': 'DPSJobstatus',
        'DPSDraftingstatus': 'DPSDrafting',
        'Draftingsubstatus': 'Draftingsubstatus',
        'DPSProductionstatus': 'DPSProductionstatus',
        'DPSProductionstatusreason': 'DPSProductionstatusreason',
        'Status1': 'Status1',
        'Status2': 'Status2',
        'Status3': 'Status3',
        'Status4': 'Status4',
        'Status5': 'Status5'

      },
      {
        'id': '2',
        'CommissionType': 'CommissionType',
        'CommissionInfo': 'CommissionInfo',
        'Status': 'Status',
        'Salutation': 'Salutation',
        'Dearline': 'Dearline',
        'LeadSource': 'LeadSource',
        'Lead': 'Lead',
        'Budget': 'Budget',
        'BuildinF': 'BuildinF',
        'BuildinS': 'BuildinS',
        'BuildSite': 'BuildSite',
        'Nearesttown': 'Nearesttown',
        'Contractor': 'Contractor',
        'Builder': 'Builder',
        'Buildertel': 'Buildertel',
        'Customerfname': 'JAS',
        'Customerlname': 'Alias',
        'Partnerfname': 'Partnerfname',
        'Partnerlname': 'Partnerlname',
        'Contractname': 'Contractname',
        'PotentialValue': 'PotentialValue',
        'DateEntered': 'DateEntered',
        'ContactNameLocked': '1/18/2018',
        'FormF': 'FormF',
        'FormS': 'true',
        'SiteServiced': 'true',
        'Siteplan': 'true',
        'DesignBudget': 'true',
        'FromwebFormf': 'FromwebFormf',
        'FromwebFormS': 'FromwebFormS',
        'Comments': 'Comments',
        'address1': 'address1',
        'Hometel': 'Hometel',
        'Address2': 'Address2',
        'Bussinesstel': 'Bussinesstel',
        'City': 'City',
        'Cellulartel': 'Cellulartel',
        'Country': 'Country',
        'email': 'email',
        'State': 'State',
        'email2': 'email2',
        'zipCode': 'zipCode',
        'ContactedVia': 'ContactedVia',
        'DPSJobstatus': 'DPSJobstatus',
        'DPSDraftingstatus': 'DPSDrafting',
        'Draftingsubstatus': 'Draftingsubstatus',
        'DPSProductionstatus': 'DPSProductionstatus',
        'DPSProductionstatusreason': 'DPSProductionstatusreason',
        'Status1': 'Status1',
        'Status2': 'Status2',
        'Status3': 'Status3',
        'Status4': 'Status4',
        'Status5': 'Status5'

      },
      {
        'id': '3',
        'CommissionType': 'CommissionType',
        'CommissionInfo': 'CommissionInfo',
        'Status': 'Status',
        'Salutation': 'Salutation',
        'Dearline': 'Dearline',
        'LeadSource': 'LeadSource',
        'Lead': 'Lead',
        'Budget': 'Budget',
        'BuildinF': 'BuildinF',
        'BuildinS': 'BuildinS',
        'BuildSite': 'BuildSite',
        'Nearesttown': 'Nearesttown',
        'Contractor': 'Contractor',
        'Builder': 'Builder',
        'Buildertel': 'Buildertel',
        'Customerfname': 'Rock',
        'Customerlname': 'Miz',
        'Partnerfname': 'Partnerfname',
        'Partnerlname': 'Partnerlname',
        'Contractname': 'Contractname',
        'PotentialValue': 'PotentialValue',
        'DateEntered': 'DateEntered',
        'ContactNameLocked': '1/18/2018',
        'FormF': 'FormF',
        'FormS': 'true',
        'SiteServiced': 'true',
        'Siteplan': 'true',
        'DesignBudget': 'true',
        'FromwebFormf': 'FromwebFormf',
        'FromwebFormS': 'FromwebFormS',
        'Comments': 'Comments',
        'address1': 'address1',
        'Hometel': 'Hometel',
        'Address2': 'Address2',
        'Bussinesstel': 'Bussinesstel',
        'City': 'City',
        'Cellulartel': 'Cellulartel',
        'Country': 'Country',
        'email': 'email',
        'State': 'State',
        'email2': 'email2',
        'zipCode': 'zipCode',
        'ContactedVia': 'ContactedVia',
        'DPSJobstatus': 'DPSJobstatus',
        'DPSDraftingstatus': 'DPSDrafting',
        'Draftingsubstatus': 'Draftingsubstatus',
        'DPSProductionstatus': 'DPSProductionstatus',
        'DPSProductionstatusreason': 'DPSProductionstatusreason',
        'Status1': 'Status1',
        'Status2': 'Status2',
        'Status3': 'Status3',
        'Status4': 'Status4',
        'Status5': 'Status5'

      },
      {
        'id': '3',
        'CommissionType': 'CommissionType',
        'CommissionInfo': 'CommissionInfo',
        'Status': 'Status',
        'Salutation': 'Salutation',
        'Dearline': 'Dearline',
        'LeadSource': 'LeadSource',
        'Lead': 'Lead',
        'Budget': 'Budget',
        'BuildinF': 'BuildinF',
        'BuildinS': 'BuildinS',
        'BuildSite': 'BuildSite',
        'Nearesttown': 'Nearesttown',
        'Contractor': 'Contractor',
        'Builder': 'Builder',
        'Buildertel': 'Buildertel',
        'Customerfname': 'Chinna',
        'Customerlname': 'Alias',
        'Partnerfname': 'Partnerfname',
        'Partnerlname': 'Partnerlname',
        'Contractname': 'Contractname',
        'PotentialValue': 'PotentialValue',
        'DateEntered': 'DateEntered',
        'ContactNameLocked': '1/18/2018',
        'FormF': 'FormF',
        'FormS': 'true',
        'SiteServiced': 'true',
        'Siteplan': 'true',
        'DesignBudget': 'true',
        'FromwebFormf': 'FromwebFormf',
        'FromwebFormS': 'FromwebFormS',
        'Comments': 'Comments',
        'address1': 'address1',
        'Hometel': 'Hometel',
        'Address2': 'Address2',
        'Bussinesstel': 'Bussinesstel',
        'City': 'City',
        'Cellulartel': 'Cellulartel',
        'Country': 'Country',
        'email': 'email',
        'State': 'State',
        'email2': 'email2',
        'zipCode': 'zipCode',
        'ContactedVia': 'ContactedVia',
        'DPSJobstatus': 'DPSJobstatus',
        'DPSDraftingstatus': 'DPSDrafting',
        'Draftingsubstatus': 'Draftingsubstatus',
        'DPSProductionstatus': 'DPSProductionstatus',
        'DPSProductionstatusreason': 'DPSProductionstatusreason',
        'Status1': 'Status1',
        'Status2': 'Status2',
        'Status3': 'Status3',
        'Status4': 'Status4',
        'Status5': 'Status5'

      },
      {
        'id': '4',
        'CommissionType': 'CommissionType',
        'CommissionInfo': 'CommissionInfo',
        'Status': 'Status',
        'Salutation': 'Salutation',
        'Dearline': 'Dearline',
        'LeadSource': 'LeadSource',
        'Lead': 'Lead',
        'Budget': 'Budget',
        'BuildinF': 'BuildinF',
        'BuildinS': 'BuildinS',
        'BuildSite': 'BuildSite',
        'Nearesttown': 'Nearesttown',
        'Contractor': 'Contractor',
        'Builder': 'Builder',
        'Buildertel': 'Buildertel',
        'Customerfname': 'XYZ',
        'Customerlname': 'XYZ',
        'Partnerfname': 'Partnerfname',
        'Partnerlname': 'Partnerlname',
        'Contractname': 'Contractname',
        'PotentialValue': 'PotentialValue',
        'DateEntered': 'DateEntered',
        'ContactNameLocked': '1/18/2018',
        'FormF': 'FormF',
        'FormS': 'true',
        'SiteServiced': 'true',
        'Siteplan': 'true',
        'DesignBudget': 'true',
        'FromwebFormf': 'FromwebFormf',
        'FromwebFormS': 'FromwebFormS',
        'Comments': 'Comments',
        'address1': 'address1',
        'Hometel': 'Hometel',
        'Address2': 'Address2',
        'Bussinesstel': 'Bussinesstel',
        'City': 'City',
        'Cellulartel': 'Cellulartel',
        'Country': 'Country',
        'email': 'email',
        'State': 'State',
        'email2': 'email2',
        'zipCode': 'zipCode',
        'ContactedVia': 'ContactedVia',
        'DPSJobstatus': 'DPSJobstatus',
        'DPSDraftingstatus': 'DPSDrafting',
        'Draftingsubstatus': 'Draftingsubstatus',
        'DPSProductionstatus': 'DPSProductionstatus',
        'DPSProductionstatusreason': 'DPSProductionstatusreason',
        'Status1': 'Status1',
        'Status2': 'Status2',
        'Status3': 'Status3',
        'Status4': 'Status4',
        'Status5': 'Status5'

      },
      {
        'id': '5',
        'CommissionType': 'CommissionType',
        'CommissionInfo': 'CommissionInfo',
        'Status': 'Status',
        'Salutation': 'Salutation',
        'Dearline': 'Dearline',
        'LeadSource': 'LeadSource',
        'Lead': 'Lead',
        'Budget': 'Budget',
        'BuildinF': 'BuildinF',
        'BuildinS': 'BuildinS',
        'BuildSite': 'BuildSite',
        'Nearesttown': 'Nearesttown',
        'Contractor': 'Contractor',
        'Builder': 'Builder',
        'Buildertel': 'Buildertel',
        'Customerfname': 'XYZ',
        'Customerlname': 'XYZ',
        'Partnerfname': 'Partnerfname',
        'Partnerlname': 'Partnerlname',
        'Contractname': 'Contractname',
        'PotentialValue': 'PotentialValue',
        'DateEntered': 'DateEntered',
        'ContactNameLocked': '1/18/2018',
        'FormF': 'FormF',
        'FormS': 'true',
        'SiteServiced': 'true',
        'Siteplan': 'true',
        'DesignBudget': 'true',
        'FromwebFormf': 'FromwebFormf',
        'FromwebFormS': 'FromwebFormS',
        'Comments': 'Comments',
        'address1': 'address1',
        'Hometel': 'Hometel',
        'Address2': 'Address2',
        'Bussinesstel': 'Bussinesstel',
        'City': 'City',
        'Cellulartel': 'Cellulartel',
        'Country': 'Country',
        'email': 'email',
        'State': 'State',
        'email2': 'email2',
        'zipCode': 'zipCode',
        'ContactedVia': 'ContactedVia',
        'DPSJobstatus': 'DPSJobstatus',
        'DPSDraftingstatus': 'DPSDrafting',
        'Draftingsubstatus': 'Draftingsubstatus',
        'DPSProductionstatus': 'DPSProductionstatus',
        'DPSProductionstatusreason': 'DPSProductionstatusreason',
        'Status1': 'Status1',
        'Status2': 'Status2',
        'Status3': 'Status3',
        'Status4': 'Status4',
        'Status5': 'Status5'

      },
      {
        'id': '6',
        'CommissionType': 'CommissionType',
        'CommissionInfo': 'CommissionInfo',
        'Status': 'Status',
        'Salutation': 'Salutation',
        'Dearline': 'Dearline',
        'LeadSource': 'LeadSource',
        'Lead': 'Lead',
        'Budget': 'Budget',
        'BuildinF': 'BuildinF',
        'BuildinS': 'BuildinS',
        'BuildSite': 'BuildSite',
        'Nearesttown': 'Nearesttown',
        'Contractor': 'Contractor',
        'Builder': 'Builder',
        'Buildertel': 'Buildertel',
        'Customerfname': 'XYZ',
        'Customerlname': 'XYZ',
        'Partnerfname': 'Partnerfname',
        'Partnerlname': 'Partnerlname',
        'Contractname': 'Contractname',
        'PotentialValue': 'PotentialValue',
        'DateEntered': 'DateEntered',
        'ContactNameLocked': '1/18/2018',
        'FormF': 'FormF',
        'FormS': 'true',
        'SiteServiced': 'true',
        'Siteplan': 'true',
        'DesignBudget': 'true',
        'FromwebFormf': 'FromwebFormf',
        'FromwebFormS': 'FromwebFormS',
        'Comments': 'Comments',
        'address1': 'address1',
        'Hometel': 'Hometel',
        'Address2': 'Address2',
        'Bussinesstel': 'Bussinesstel',
        'City': 'City',
        'Cellulartel': 'Cellulartel',
        'Country': 'Country',
        'email': 'email',
        'State': 'State',
        'email2': 'email2',
        'zipCode': 'zipCode',
        'ContactedVia': 'ContactedVia',
        'DPSJobstatus': 'DPSJobstatus',
        'DPSDraftingstatus': 'DPSDrafting',
        'Draftingsubstatus': 'Draftingsubstatus',
        'DPSProductionstatus': 'DPSProductionstatus',
        'DPSProductionstatusreason': 'DPSProductionstatusreason',
        'Status1': 'Status1',
        'Status2': 'Status2',
        'Status3': 'Status3',
        'Status4': 'Status4',
        'Status5': 'Status5'

      },
      {
        'id': '7',
        'CommissionType': 'CommissionType',
        'CommissionInfo': 'CommissionInfo',
        'Status': 'Status',
        'Salutation': 'Salutation',
        'Dearline': 'Dearline',
        'LeadSource': 'LeadSource',
        'Lead': 'Lead',
        'Budget': 'Budget',
        'BuildinF': 'BuildinF',
        'BuildinS': 'BuildinS',
        'BuildSite': 'BuildSite',
        'Nearesttown': 'Nearesttown',
        'Contractor': 'Contractor',
        'Builder': 'Builder',
        'Buildertel': 'Buildertel',
        'Customerfname': 'XYZ',
        'Customerlname': 'XYZ',
        'Partnerfname': 'Partnerfname',
        'Partnerlname': 'Partnerlname',
        'Contractname': 'Contractname',
        'PotentialValue': 'PotentialValue',
        'DateEntered': 'DateEntered',
        'ContactNameLocked': '1/18/2018',
        'FormF': 'FormF',
        'FormS': 'true',
        'SiteServiced': 'true',
        'Siteplan': 'true',
        'DesignBudget': 'true',
        'FromwebFormf': 'FromwebFormf',
        'FromwebFormS': 'FromwebFormS',
        'Comments': 'Comments',
        'address1': 'address1',
        'Hometel': 'Hometel',
        'Address2': 'Address2',
        'Bussinesstel': 'Bussinesstel',
        'City': 'City',
        'Cellulartel': 'Cellulartel',
        'Country': 'Country',
        'email': 'email',
        'State': 'State',
        'email2': 'email2',
        'zipCode': 'zipCode',
        'ContactedVia': 'ContactedVia',
        'DPSJobstatus': 'DPSJobstatus',
        'DPSDraftingstatus': 'DPSDrafting',
        'Draftingsubstatus': 'Draftingsubstatus',
        'DPSProductionstatus': 'DPSProductionstatus',
        'DPSProductionstatusreason': 'DPSProductionstatusreason',
        'Status1': 'Status1',
        'Status2': 'Status2',
        'Status3': 'Status3',
        'Status4': 'Status4',
        'Status5': 'Status5'

      },
      {
        'id': '8',
        'CommissionType': 'CommissionType',
        'CommissionInfo': 'CommissionInfo',
        'Status': 'Status',
        'Salutation': 'Salutation',
        'Dearline': 'Dearline',
        'LeadSource': 'LeadSource',
        'Lead': 'Lead',
        'Budget': 'Budget',
        'BuildinF': 'BuildinF',
        'BuildinS': 'BuildinS',
        'BuildSite': 'BuildSite',
        'Nearesttown': 'Nearesttown',
        'Contractor': 'Contractor',
        'Builder': 'Builder',
        'Buildertel': 'Buildertel',
        'Customerfname': 'XYZ',
        'Customerlname': 'XYZ',
        'Partnerfname': 'Partnerfname',
        'Partnerlname': 'Partnerlname',
        'Contractname': 'Contractname',
        'PotentialValue': 'PotentialValue',
        'DateEntered': 'DateEntered',
        'ContactNameLocked': '1/18/2018',
        'FormF': 'FormF',
        'FormS': 'true',
        'SiteServiced': 'true',
        'Siteplan': 'true',
        'DesignBudget': 'true',
        'FromwebFormf': 'FromwebFormf',
        'FromwebFormS': 'FromwebFormS',
        'Comments': 'Comments',
        'address1': 'address1',
        'Hometel': 'Hometel',
        'Address2': 'Address2',
        'Bussinesstel': 'Bussinesstel',
        'City': 'City',
        'Cellulartel': 'Cellulartel',
        'Country': 'Country',
        'email': 'email',
        'State': 'State',
        'email2': 'email2',
        'zipCode': 'zipCode',
        'ContactedVia': 'ContactedVia',
        'DPSJobstatus': 'DPSJobstatus',
        'DPSDraftingstatus': 'DPSDrafting',
        'Draftingsubstatus': 'Draftingsubstatus',
        'DPSProductionstatus': 'DPSProductionstatus',
        'DPSProductionstatusreason': 'DPSProductionstatusreason',
        'Status1': 'Status1',
        'Status2': 'Status2',
        'Status3': 'Status3',
        'Status4': 'Status4',
        'Status5': 'Status5'

      },
      {
        'id': '9',
        'CommissionType': 'CommissionType',
        'CommissionInfo': 'CommissionInfo',
        'Status': 'Status',
        'Salutation': 'Salutation',
        'Dearline': 'Dearline',
        'LeadSource': 'LeadSource',
        'Lead': 'Lead',
        'Budget': 'Budget',
        'BuildinF': 'BuildinF',
        'BuildinS': 'BuildinS',
        'BuildSite': 'BuildSite',
        'Nearesttown': 'Nearesttown',
        'Contractor': 'Contractor',
        'Builder': 'Builder',
        'Buildertel': 'Buildertel',
        'Customerfname': 'XYZ',
        'Customerlname': 'XYZ',
        'Partnerfname': 'Partnerfname',
        'Partnerlname': 'Partnerlname',
        'Contractname': 'Contractname',
        'PotentialValue': 'PotentialValue',
        'DateEntered': 'DateEntered',
        'ContactNameLocked': '1/18/2018',
        'FormF': 'FormF',
        'FormS': 'true',
        'SiteServiced': 'true',
        'Siteplan': 'true',
        'DesignBudget': 'true',
        'FromwebFormf': 'FromwebFormf',
        'FromwebFormS': 'FromwebFormS',
        'Comments': 'Comments',
        'address1': 'address1',
        'Hometel': 'Hometel',
        'Address2': 'Address2',
        'Bussinesstel': 'Bussinesstel',
        'City': 'City',
        'Cellulartel': 'Cellulartel',
        'Country': 'Country',
        'email': 'email',
        'State': 'State',
        'email2': 'email2',
        'zipCode': 'zipCode',
        'ContactedVia': 'ContactedVia',
        'DPSJobstatus': 'DPSJobstatus',
        'DPSDraftingstatus': 'DPSDrafting',
        'Draftingsubstatus': 'Draftingsubstatus',
        'DPSProductionstatus': 'DPSProductionstatus',
        'DPSProductionstatusreason': 'DPSProductionstatusreason',
        'Status1': 'Status1',
        'Status2': 'Status2',
        'Status3': 'Status3',
        'Status4': 'Status4',
        'Status5': 'Status5'

      },
      {
        'id': '10',
        'CommissionType': 'CommissionType',
        'CommissionInfo': 'CommissionInfo',
        'Status': 'Status',
        'Salutation': 'Salutation',
        'Dearline': 'Dearline',
        'LeadSource': 'LeadSource',
        'Lead': 'Lead',
        'Budget': 'Budget',
        'BuildinF': 'BuildinF',
        'BuildinS': 'BuildinS',
        'BuildSite': 'BuildSite',
        'Nearesttown': 'Nearesttown',
        'Contractor': 'Contractor',
        'Builder': 'Builder',
        'Buildertel': 'Buildertel',
        'Customerfname': 'XYZ',
        'Customerlname': 'XYZ',
        'Partnerfname': 'Partnerfname',
        'Partnerlname': 'Partnerlname',
        'Contractname': 'Contractname',
        'PotentialValue': 'PotentialValue',
        'DateEntered': 'DateEntered',
        'ContactNameLocked': '1/18/2018',
        'FormF': 'FormF',
        'FormS': 'true',
        'SiteServiced': 'true',
        'Siteplan': 'true',
        'DesignBudget': 'true',
        'FromwebFormf': 'FromwebFormf',
        'FromwebFormS': 'FromwebFormS',
        'Comments': 'Comments',
        'address1': 'address1',
        'Hometel': 'Hometel',
        'Address2': 'Address2',
        'Bussinesstel': 'Bussinesstel',
        'City': 'City',
        'Cellulartel': 'Cellulartel',
        'Country': 'Country',
        'email': 'email',
        'State': 'State',
        'email2': 'email2',
        'zipCode': 'zipCode',
        'ContactedVia': 'ContactedVia',
        'DPSJobstatus': 'DPSJobstatus',
        'DPSDraftingstatus': 'DPSDrafting',
        'Draftingsubstatus': 'Draftingsubstatus',
        'DPSProductionstatus': 'DPSProductionstatus',
        'DPSProductionstatusreason': 'DPSProductionstatusreason',
        'Status1': 'Status1',
        'Status2': 'Status2',
        'Status3': 'Status3',
        'Status4': 'Status4',
        'Status5': 'Status5'

      }

            
    ];

    public static user = [
        {
            'id'              : '5725a6802d10e277a0f35724',
            'name'            : 'John Doe',
            'avatar'          : 'assets/images/avatars/profile.jpg',
            'starred'         : [
                '1',
                '2',
                '3',
                '4',
                '5'
            ],
            'frequentContacts': [
                '6',
                '7',
                '8',
                '9',
                '10',
                '2',
                '1',
                '3'
            ],
            'groups'          : [
                {
                    'id'        : '2',
                    'name'      : 'Friends',
                    'contactIds': [
                        '3',
                        '4',
                        '5'
                    ]
                },
                {
                    'id'        : '1',
                    'name'      : 'Clients',
                    'contactIds': [
                        '5',
                        '6',
                        '8',
                        '10'
                    ]
                },
                {
                    'id'        : '3',
                    'name'      : 'Recent Workers',
                    'contactIds': [
                        '9',
                        '7',
                        '4',
                        '1'
                    ]
                }
            ]
        }
    ];
}
